// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body-container': string;
  'links': string;
  'nav': string;
  'nav-left': string;
  'nav-left-stack': string;
  'nav-right': string;
  'nav-right-stack': string;
  'search-container': string;
  'search-toolbar': string;
  'username': string;
}
export const cssExports: CssExports;
export default cssExports;
